### ISSUE TITLE
White Blood Cell Towers

### ISSUE THREAD

**Issue by PlotArmorStudios** [PlotArmorStudios/GJL_Jam_2022#27]
- [x] Deal damage to boss/minions
- [x] Deativate/Despawn after x number of seconds

**Comment by PlotArmorStudios** [comment]
Projectile and turret are implemented in main. Go ahead and merge main with your branch to get the updates. Let me know if you have any questions!

**Comment by AndrewLetailleur** [comment]
Pushed a pull request to main, aiming just works. It's 'sample tagged' for Enemy tag, but 'low scope lens' that could just as easily with some code edits, apply to just a "Boss" target. Or, be to the lens of the "nearest target" with the viable tag. Only thing needed is two parts. One critical, one minor.

Critical: Check to ensure the projectiles DAMAGE the Enemy (or Minions).
Mild: S/Lerp the 'aim transform', so it doesn't instantly "snap" rotate, aim wise?
