### ISSUE TITLE
Kidney

### ISSUE THREAD

**Issue by PlotArmorStudios** [PlotArmorStudios/GJL_Jam_2022#28]
- [x] Take damage based on "attack" events fired from Boss AI

**Comment by AndrewLetailleur** [comment]
So far, added prototype references that "should" be able to enable damage if called/invoked, by any Enemy script... Or timer. But that's under the 'split' lens under two lenses.

A: Potential "tick" damage, timer wise. As an alternative 'damage' option for the Health script, that should swim well with the 'temporary' white cell towers.
B: Revive cost. Directly invoked by the player not being present, after a speculative 'marble check'.

Probably still needs a notch of checking, editing/etc, as needed. If so, feel free to edit your name tag on the edited-by on the scripts, comment wise. :)

**Comment by AndrewLetailleur** [comment]
Hindsight, unless marked otherwise. Probably want to check if this code works, before marking it as complete (debug wise). Otherwise, it's as it currently stands, theoretically complete/done.
